#!/bin/bash
# Complete automation setup for the logging system

echo ""
echo "🎉 === AUTOMATION SETUP COMPLETE! ==="
echo ""
echo "✅ Services installed and started"
echo "✅ Automation timers enabled"
echo "✅ Control scripts created"
echo ""
echo "📋 Automation Schedule:"
echo "  • Log collection: Every 30 minutes"
echo "  • Alert checking: Every hour"
echo "  • Git upload: Every 2 hours"
echo "  • Daily report: 11:30 PM daily"
echo ""
echo "🎛️ Control your system:"
echo "  ~/simple-logs/control-system.sh [command]"
echo ""
echo "📊 Check status:"
echo "  ~/check-logging-status.sh"
echo ""
echo "🌐 Start dashboard:"
echo "  cd ~/simple-logs && python3 dashboard.py"
echo ""
echo "🔄 To reload services after changes:"
echo "  systemctl --user daemon-reload"
echo ""
echo "📈 View timer status:"
echo "  systemctl --user list-timers | grep simple-logs"